### ISSUE TITLE
从 npm 安装后不可用

### ISSUE THREAD

**Issue by XerWandeRer** [bearyinnovative/bearychat.js#11]
从 npm 中安装后，仍然提示 `Error: Cannot find module 'bearychat'`。

看了一眼 `package.json` 文件的第 5 行：
```json
"main": "dist/index.js",
```
然而却没有 `dist` 目录。

**Comment by bcho** [comment]
Hi, 0.0.2 版本的发布没有把 `dist/` 加入到 npm publish 中，这个问题已经在 [0.0.3](https://github.com/bearyinnovative/bearychat.js/releases/tag/0.0.3) 中修复了。你可以通过 

```
$ npm install bearychat@0.0.3
```

来解决

感谢你的反馈 =D
